# Nombre del workflow
name: CI Jobs Pipeline

# Define los eventos que activan el workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define los jobs del workflow
jobs:
  # Job 1: Build de la aplicación
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Application
        run: |
          echo "Building the application..."
          python setup.py sdist bdist_wheel
          echo "Build complete!"

  # Job 2: Test de la aplicación (solo si el job 'build' pasa)
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest test_script_corrected.py

  # Job 3: Comprobamos la calidad del código si pasamos los tests
  quality:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run Flake8 for code quality
        run: |
          flake8 . --max-line-length=79     

      - name: Check code format with black
        run: |
          black --check .

      - name: Run Pylint for code analysis
        run: |
          python -m pylint main.py
#Meter la calidad de código después de los tests
